#!/usr/bin/env python

import sys

for line in sys.stdin:
    try:
        line = line.strip().split()
        prodid, recid, discount, usrSex, usrAgeGroup, usrEducation, usrIncomeGroup, compraEfetuada = line
        print prodid, recid, discount, compraEfetuada, 1
    except:
        pass

