#!/usr/bin/env python

import sys

currFstKey = None
currSndKey = None
fstKeyCount = 0
sndKeyCount = 0

def getFirstKey(line):
    return ' '.join(line.split()[0:-2]) + ' *** * '


def computeCount(key, currentKey, count):
    if key == currentKey:
        return currentKey, count + 1
    else:
        if currentKey is not None:
            print currentKey, count
        return key, 1

for line in sys.stdin:
    data = line.strip()

    fstKey = getFirstKey(data)
    sndKey = data

    currFstKey, fstKeyCount = computeCount(fstKey, currFstKey, fstKeyCount)
    currSndKey, sndKeyCount = computeCount(sndKey, currSndKey, sndKeyCount)



