#!/usr/bin/env python

import sys

currKey = None
currCount = 0

def computeCount(key, count, currentKey, currentCount):
    if key == currentKey:
        return currentKey, currentCount + count
    else:
        if currentKey is not None:
            print currentKey, currentCount
        return key, count


def getData(data):
    xs = data.split()
    key = ' '.join(xs[0:-1])
    try:
        count = int(xs[0].strip())
        return key, count
    except ValueError:
        return key, 0

for line in sys.stdin:
    try:
        data = line.strip()
        key, count = getData(data)
        currKey, currCount = computeCount(key, count, currKey, currCount)
    except:
        pass
