#!/usr/bin/env python

import sys

currKey = None
currCount = 0

def computeCount(key, count, currentKey, currentCount):
    if key == currentKey:
        return currentKey, currentCount + count
    else:
        if currentKey is not None:
            print currentKey, '#', currentCount
        return key, count


def getData(data, sep = '#'):
    key, count = data.split(sep)
    try:
        count = int(count.strip())
        return key, count
    except ValueError:
        return key, 0

for line in sys.stdin:
    data = line.strip()
    key, count = getData(data)
    currKey, currCount = computeCount(key, count, currKey, currCount)
